# Generated by Django 2.2.5 on 2019-09-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='categories',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='note',
            name='images',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='note',
            name='links',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(db_index=True, max_length=55, unique=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='url',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
