# Generated by Django 2.2.5 on 2019-09-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20190907_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='categories',
            field=models.CharField(default='No categories', max_length=1000),
        ),
        migrations.AlterField(
            model_name='note',
            name='images',
            field=models.CharField(default='No images', max_length=1000),
        ),
        migrations.AlterField(
            model_name='note',
            name='links',
            field=models.CharField(default='No links', max_length=1000),
        ),
    ]
