# Generated by Django 2.2.5 on 2019-09-09 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_auto_20190909_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
    ]
