# Generated by Django 2.2.5 on 2019-09-09 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_note_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
    ]
