# Generated by Django 2.2.5 on 2019-09-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_remove_note_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='categories',
            field=models.TextField(default='No categories'),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='images',
            field=models.TextField(default='No images'),
        ),
        migrations.AlterField(
            model_name='note',
            name='links',
            field=models.TextField(default='No links'),
        ),
        migrations.AlterField(
            model_name='note',
            name='url',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
